config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :books
    end
  end

  post 'users/impersonate' => 'users#impersonate', as: :impersonate
  get 'users/stop_impersonating' => 'users#stop_impersonating', as: :stop_impersonating
  get 'users' => 'users#index'
  patch 'users/:id' => 'users#update'
  post 'users/admin' => 'users#create'
  post 'users/invite' => 'users#invite'
  get 'email_prefs/:id' => 'email_prefs#show', as: :email_pref
  patch 'email_prefs/:id' => 'email_prefs#update', as: :email_prefs
  get 'ratings/index'
  get 'books/users/:user_id' => 'books#user', as: :books_user

  devise_for :users

  resources :books do
    resources :ratings, only: [:update, :new]
    resources :reviews, only: [:index]
  end
  resources :follows, only: [:update, :new, :create, :destroy]
  resources :reviews
  resources :authors

  root 'books#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :ratings
  has_many :books
  has_many :follows
  has_one :email_prefs

  def generate_api_key
    loop do
      token = SecureRandom.base64.tr('+/=', 'Qat')
      break token unless User.exists?(api_key: token)
    end
  end

  def update_api_key
    update_attribute(:api_key, generate_api_key)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter only: [:index, :impersonate] do
    redirect_to root_path unless current_user.try(:admin?)
  end
  before_action :check_email, only: [:invite]

  def index
    @users = User.all.paginate(:page => params[:page])
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: 'User privileges changed.' }
        format.json { render :show, status: :ok }
      else
        format.html { redirect_to users_path, error: 'That update was declined.' }
        format.json {}
      end
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'Success!'
      flash[:notice] = 'Admin was added.'
      Notification.welcome_email(@user).deliver
    else
      flash[:error] = 'There was a problem creating the admin.'
    end
    # flash.keep
    redirect_to root_path
  end

  def impersonate
    user = User.find(params[:user][:id])
    impersonate_user(user)
    redirect_to root_path
  end

  def stop_impersonating
    stop_impersonating_user
    redirect_to root_path
  end

  def invite
    options = { email: params[:user][:email], from: current_user.email, admin: false }
    if params[:user][:admin].present? && params[:user][:admin] == '1'
      options[:admin] = true
    end
    Notification.member_invite(options).deliver
    flash[:success] = 'Member invited!'
    redirect_to root_path
  end

  private

  def check_email
    if params[:user][:email].blank?
      redirect_to root_path, notice: 'You must enter an email address.'
    end
  end
    
  def set_user
    begin
      @user = User.find(params[:id])
    rescue
      redirect_to root_path
    end
  end

  def user_params
    params[:user].permit(:email,
                         :password,
                         :password_confirmation,
                         :admin,
                         :restricted)
  end
end

app/views/users/_form.html.haml
= form_for User.new, url: users_admin_path do |f|
  %fieldset
    %h4 Add user
    .form-group
      = f.label :email
      = f.email_field :email, class: 'form-control'  
    .field
      = f.label :password
      = f.password_field :password, class: 'form-control'  
    .field
      = f.label :password_confirmation
      = f.password_field :password_confirmation, class: 'form-control'
    .field
      = f.label :admin
      = f.check_box :admin, class: 'form-control'
    
  .actions
    = f.submit 'Add', class: 'btn btn-primary'

app/views/users/_invite_form.html.haml
= form_for User.new, url: users_invite_path, :html => { id: 'invite' } do |f|
  %h4= 'Invite a member!'
  .form-group
    = f.label :email
    = f.email_field :email, id: 'invite_email', class: 'form-control'
  - if current_user.admin?
    .field
      = f.label :admin
      = f.check_box :admin, id: 'invite_admin'
  .actions
    = f.submit 'Invite', class: 'btn btn-success'

app/views/users/index.html.haml
%h1 Users

- if @users.count > 0
  %h3= "#{@users.count} users found:" 
  %table.table
    %tr
      %th Restricted
      %th Email
      %th Admin
    - @users.each do |user|
      %tr
        %td= check_box_tag "user_#{user.id}_restricted", 1, user.restricted?, class: 'restricted', data: { user_id: user.id, url: users_path, method: 'PATCH' }
        %td= user.email
        %td= check_box_tag "user_#{user.id}_admin", 1, user.admin?, class: 'admin', data: { user_id: user.id, url: users_path, method: 'PATCH' }
  = will_paginate @users
- else
  %p No users! 
  = link_to 'Invite admin', new_book_path