config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :books
    end
  end

  post 'users/impersonate' => 'users#impersonate', as: :impersonate
  get 'users/stop_impersonating' => 'users#stop_impersonating', as: :stop_impersonating
  get 'users' => 'users#index'
  patch 'users/:id' => 'users#update'
  post 'users/admin' => 'users#create'
  post 'users/invite' => 'users#invite'
  get 'email_prefs/:id' => 'email_prefs#show', as: :email_pref
  patch 'email_prefs/:id' => 'email_prefs#update', as: :email_prefs
  get 'ratings/index'
  get 'books/users/:user_id' => 'books#user', as: :books_user

  devise_for :users

  resources :books do
    resources :ratings, only: [:update, :new]
    resources :reviews, only: [:index]
  end
  resources :follows, only: [:update, :new, :create, :destroy]
  resources :reviews
  resources :authors

  root 'books#index'

end

app/views/shared/_auth_links.html.haml
= "You are signed in as: #{current_user.email}" if current_user
= '[Admin]' if current_user.try(:admin?)
= devise_links

app/views/shared/_book_rating.html.haml
.star{:id => "rating_book_#{book.id}", :data => {'score' => book.saved_rating, 'book-id' => book.id}}

app/views/shared/_book_user_rated.html.haml
.star{:id => "rating_book_#{book.id}_user_#{user.id}", :data => {'score' => "#{score}", 'book-id' => book.id}}

app/views/shared/_book_user_rating.html.haml
- if book && book.id.present?
  .user_star{:data => {'score' => book.user_rating(current_user), 'book-id' => book.id, 'url' => "/books/#{book.id}/ratings/new", :readonly => current_user.restricted?}}
- else
  .new_star

app/views/shared/_flash.html.haml
- flash.each do |type, message|
  %div{:class => "alert #{bootstrap_class_for(type)} fade in"}
    %button.close{"data-dismiss" => "alert"} ×
    = message

app/views/shared/_impersonate_links.html.haml
- if current_user.try(:admin?)
  %impersonate
    = form_for :user, :as => :post, :url => impersonate_path do |f|
      .form-group
        %label= 'View as:'
        = select(:user, :id, options_for_select(User.all.map{|u| [u.email, u.id]}), {}, {:class => "form-control"})
      .actions
        = f.submit 'Impersonate', :class => 'btn btn-warning'

app/views/shared/_nav_links_html.haml
%li= link_to 'Products', products_path
- if current_user && current_user.admin?
  %li= link_to 'New Product', new_product_path
  %li= link_to 'Shops', shops_path
  %li= link_to 'Add shop', new_shop_path
  %li= link_to 'Users', users_path
  %li= link_to 'Accounts', accounts_path
  %li= link_to 'Accounting Entries', entries_path

app/views/shared/_search_form.html.haml
#books_search_form
  = form_tag books_path, :method => :get do
    #books_search_form_searchbox
      .input-group
        = text_field_tag :search, params[:search], :placeholder => 'Search ...', class: 'form-control'
        .input-group-btn
          %button.btn.btn-default{:type => "submit", :id => 'search_button'}
            %i.fa.fa-search

app/views/shared/_true_user_links.html.haml
- if current_user != true_user
  You (#{true_user.email}) are signed in as #{current_user.email}
  = link_to "Back to admin", stop_impersonating_path