config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :books
    end
  end

  post 'users/impersonate' => 'users#impersonate', as: :impersonate
  get 'users/stop_impersonating' => 'users#stop_impersonating', as: :stop_impersonating
  get 'users' => 'users#index'
  patch 'users/:id' => 'users#update'
  post 'users/admin' => 'users#create'
  post 'users/invite' => 'users#invite'
  get 'email_prefs/:id' => 'email_prefs#show', as: :email_pref
  patch 'email_prefs/:id' => 'email_prefs#update', as: :email_prefs
  get 'ratings/index'
  get 'books/users/:user_id' => 'books#user', as: :books_user

  devise_for :users

  resources :books do
    resources :ratings, only: [:update, :new]
    resources :reviews, only: [:index]
  end
  resources :follows, only: [:update, :new, :create, :destroy]
  resources :reviews
  resources :authors

  root 'books#index'

end

app/models/follow.rb
class Follow < ActiveRecord::Base
  belongs_to :user
  belongs_to :book
  after_save :validate_selections

  private

  def validate_selections
    unless rating? || review?
      Follow.where('book_id = ? AND user_id = ?', book_id, user_id).delete_all
    end
  end

end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :set_follow, only: [:update, :destroy]
  before_filter only: [:new] do
    redirect_to :new_user_session unless current_user
  end

  def index
  end

  def create
    @follow = Follow.new(follow_params)
    if @follow.save
      redirect_to @follow.book, notice: 'Follow preferences updated.'
    else
      redirect_to books, notice: 'Your preferences could not be updated.'
    end
  end

  def update
    @follow = Follow.find(params[:id])
    book = @follow.book
    if @follow.update(follow_params)
      redirect_to book, notice: 'Follow preferences updated.'
    else
      redirect_to book, notice: 'Your preferences could not be updated.'
    end
  end

  def destroy
    @follow.destroy
    render json: {}, status: :no_content
  end
  private

  def set_follow
    begin
      @follow = Follow.find(params[:id])
    rescue
      redirect_to books_path
    end
  end
  # Never trust parameters from the scary internet, only allow the white list through.
  def follow_params
    params[:follow].permit(:rating, :review, :book_id, :user_id)
  end
end

app/views/follows/_follows_fields.html.haml
%fieldset
  .field
    = f.label :ratings
    = f.check_box :rating
  .field
    = f.label :reviews
    = f.check_box :review
  = f.hidden_field :user_id, value: current_user.id

app/views/follows/_form.html.haml
= form_for follow do |f|
  = render 'follows/follows_fields', :f => f
    
  .actions
    = f.submit 'Update'

app/views/follows/_form_new.html.haml
= form_for Follow.new, url: follows_path do |f|
  %fieldset
    .field
      = f.label :ratings
      = f.check_box :rating
    .field
      = f.label :reviews
      = f.check_box :review
    = f.hidden_field :book_id, value: @book.id
    = f.hidden_field :user_id, value: current_user.id if current_user

  .actions
    = f.submit 'Follow'