config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :books
    end
  end

  post 'users/impersonate' => 'users#impersonate', as: :impersonate
  get 'users/stop_impersonating' => 'users#stop_impersonating', as: :stop_impersonating
  get 'users' => 'users#index'
  patch 'users/:id' => 'users#update'
  post 'users/admin' => 'users#create'
  post 'users/invite' => 'users#invite'
  get 'email_prefs/:id' => 'email_prefs#show', as: :email_pref
  patch 'email_prefs/:id' => 'email_prefs#update', as: :email_prefs
  get 'ratings/index'
  get 'books/users/:user_id' => 'books#user', as: :books_user

  devise_for :users

  resources :books do
    resources :ratings, only: [:update, :new]
    resources :reviews, only: [:index]
  end
  resources :follows, only: [:update, :new, :create, :destroy]
  resources :reviews
  resources :authors

  root 'books#index'

end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Bookopotamus"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    %nav#myNavbar.navbar.navbar-default.navbar-inverse.navbar-fixed-top{:role => "navigation"}
      .container-fluid
        .navbar-header
          %button.navbar-toggle{"data-target" => "#navbarCollapse", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to 'Bookopotamus', root_path, class: 'navbar-brand'
        / Collect the nav links, forms, and other content for toggling
        #navbarCollapse.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li= link_to 'Books', books_path
            %li= link_to 'My books', books_user_path(current_user) if current_user
            %li= link_to 'Add a book', new_book_path if current_user
            %li= link_to 'Users', users_path if current_user.try(:admin?)
          %ul.nav.navbar-nav.navbar-right
            %li
              = link_to "#{current_user.email}#{current_user_admin(current_user)}", email_pref_path(current_user) if current_user
            %li= link_to 'Log In', new_user_session_path unless current_user
            %li= link_to 'Logout', destroy_user_session_path, method: :delete if current_user

    .container-fluid
      .row
        .col-md-3
          .well.sidebar-login
            %h4= 'Log in'
            = render 'devise/shared/new' unless current_user
            - if current_user
              %p= link_to "#{current_user.email}#{current_user_admin(current_user)}", email_pref_path(current_user)
              %p= link_to 'Logout', destroy_user_session_path, method: :delete
              %hr
              %p= link_to 'Add a book', new_book_path
          - if current_user.try(:admin?)
            .well.sidebar.nav
              = render 'users/form'
            .well.sidebar.nav
              = render 'shared/impersonate_links'
          - if current_user && current_user != true_user
            .well.sidebar.nav
              = render 'shared/true_user_links'
          - if current_user
            .well.sidebar.nav
              = render 'users/invite_form'
        .col-md-9
          = render 'shared/flash'
          #search_box.pull-right.col-md-4
            = render 'shared/search_form'
          .main
            = yield
    
      %footer
        %p
          &copy; 
          =link_to 'Lynne Cooney', 'http://ilynne.com'
          ="2014-#{DateTime.now.year}."